(namespace
  ("sxml#"

   ;; sxml-tools

   sxml:find-name-separator
   filter-and-map
   check-list
   make-char-quotator
   sxml:attr-list-node
   sxml:attr-as-list
   sxml:aux-list-node
   sxml:aux-as-list
   sxml:error
   sxml:empty-element?
   sxml:shallow-normalized?
   sxml:normalized?
   sxml:shallow-minimized?
   sxml:minimized?
   sxml:name
   sxml:element-name
   sxml:node-name
   sxml:ncname
   sxml:name->ns-id
   sxml:content
   sxml:text
   sxml:content-raw
   sxml:attr-list-u
   sxml:aux-list
   sxml:aux-list-u
   sxml:aux-node
   sxml:aux-nodes
   sxml:attr
   sxml:attr-from-list
   sxml:num-attr
   sxml:attr-u
   sxml:ns-list
   sxml:ns-id->nodes
   sxml:ns-id->uri
   sxml:ns-uri->nodes
   sxml:ns-uri->id
   sxml:ns-id
   sxml:ns-uri
   sxml:ns-prefix
   sxml:change-content!
   sxml:change-content
   sxml:change-attrlist
   sxml:change-attrlist!
   sxml:change-name!
   sxml:change-name
   sxml:add-attr
   sxml:add-attr!
   sxml:change-attr
   sxml:change-attr!
   sxml:set-attr
   sxml:set-attr!
   sxml:add-aux
   sxml:add-aux!
   sxml:squeeze!
   sxml:squeeze
   sxml:clean
   select-first-kid
   sxml:node-parent
   sxml:add-parents
   sxml:lookup
   sxml:attr->xml
   sxml:string->xml
   sxml:sxml->xml
   sxml:attr->html
   sxml:string->html
   sxml:non-terminated-html-tag?
   sxml:sxml->html

   ;; serializer

   srl:map-append
   srl:apply-string-append
   srl:assoc-cdr-string=
   srl:member-ci
   srl:mem-pred
   srl:char-nl
   srl:newline
   srl:select-kids
   srl:separate-list
   srl:clean-fragments
   srl:display-fragments-2nesting
   srl:split
   srl:atomic->string
   srl:empty-elem?
   srl:conventional-ns-prefixes
   srl:namespace-assoc-for-elem
   srl:ns-assoc-for-top
   srl:extract-original-prefix-binding
   srl:update-space-specifier
   srl:normalize-sequence
   srl:xml-char-escaped
   srl:string->cdata-section
   srl:escape-alist-char-data
   srl:escape-alist-html-att
   srl:string->escaped
   srl:string->char-data
   srl:string->att-value
   srl:string->html-att
   srl:shtml-entity->char-data
   srl:qname->string
   srl:attribute->str-lst
   srl:namespace-decl->str-lst
   srl:comment->str-lst
   srl:processing-instruction->str-lst
   srl:name->qname-component
   srl:construct-start-end-tags
   srl:node->nested-str-lst-recursive
   srl:display-node-out-recursive
   srl:make-xml-decl
   srl:top->nested-str-lst
   srl:display-top-out
   srl:sxml->string
   srl:display-sxml
   srl:parameterizable
   srl:sxml->xml
   srl:sxml->xml-noindent
   srl:sxml->html
   srl:sxml->html-noindent

   ;; sxpath-lib

   nodeset?
   as-nodeset
   sxml:element?
   ntype-names??
   ntype??
   ntype-namespace-id??
   sxml:complement
   node-eq?
   node-equal?
   node-pos
   sxml:filter
   take-until
   take-after
   map-union
   node-reverse
   node-trace
   select-kids
   node-self
   node-join
   node-reduce
   node-or
   node-closure
   sxml:node?
   sxml:attr-list
   sxml:attribute
   sxml:child
   sxml:parent
   node-parent
   sxml:child-nodes
   sxml:child-elements

   ;; sxpath-core

   sxpath
   if-sxpath
   if-car-sxpath
   car-sxpath
   sxml:id-alist

   ;; sxpath-ext

   sxml:string
   sxml:boolean
   sxml:number
   sxml:string-value
   sxml:id
   sxml:nested-loop-join
   sxml:list-head
   sxml:merge-sort
   sxml:merge-sort-join
   sxml:charlst->branch
   sxml:string->tree
   sxml:add-string-to-tree
   sxml:string-in-tree?
   sxml:radix-sort-join
   sxml:equality-cmp
   sxml:equal?
   sxml:not-equal?
   sxml:relational-cmp
   sxml:ancestor
   sxml:ancestor-or-self
   sxml:descendant
   sxml:descendant-or-self
   sxml:following
   sxml:following-sibling
   sxml:namespace
   sxml:preceding
   sxml:preceding-sibling

   ;; txpath

   sxml:xpointer-runtime-error
   sxml:xpath-nodeset-filter
   sxml:arithmetic-eval
   sxml:core-last
   sxml:core-position
   sxml:core-count
   sxml:core-id
   sxml:core-local-name
   sxml:core-namespace-uri
   sxml:core-name
   sxml:core-string
   sxml:core-concat
   sxml:core-starts-with
   sxml:core-contains
   sxml:core-substring-before
   sxml:core-substring-after
   sxml:core-substring
   sxml:core-string-length
   sxml:core-normalize-space
   sxml:core-translate
   sxml:core-boolean
   sxml:core-not
   sxml:core-true
   sxml:core-false
   sxml:core-lang
   sxml:core-number
   sxml:core-sum
   sxml:core-floor
   sxml:core-ceiling
   sxml:core-round
   sxml:classic-params
   sxml:api-helper0
   sxml:classic-res
   sxml:api-helper
   sxml:xpath
   sxml:xpointer
   sxml:xpath-expr
   sxml:xpath+root+vars
   sxml:xpointer+root+vars
   sxml:xpath+root
   txpath
   sxml:api-index-helper
   sxml:xpath+index
   sxml:xpointer+index

   ;; xpath-parser

   txp:param-value
   txp:error?
   sxml:xpointer-parse-error
   sxml:xpointer-parse-warning
   txp:semantic-errs-detected?
   txp:signal-semantic-error
   sxml:whitespace
   sxml:delimiter
   sxml:non-first?
   sxml:skip-ws
   sxml:assert-end-of-path
   sxml:parse-check
   sxml:parse-check-sequence
   sxml:parse-assert
   sxml:parse-ncname
   sxml:parse-name
   sxml:parse-qname
   sxml:parse-natural
   sxml:parse-literal
   sxml:parse-number
   txp:parameterize-parser
 ))
